spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 30000
  sql:
    init:
      mode: always              # Executa toda inicializa��o SQL no startup
      platform: postgres        # Procura schema-postgres.sql e data-postgres.sql
      separator: "@@"             # <- Separa os statements de TOPO
      continue-on-error: true    # ignora erros não-críticos em reruns

  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      write-dates-as-timestamps: false

logging.level:
  root: INFO
  br.com.solbank: DEBUG